// -------------------------------------------------------------------------------- 
// -------------------------------------------------------------------------------- 
// Power Catagory : Synergist_Support 
// 			Worksheet : Synergist_Support 
// -------------------------------------------------------------------------------- 
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1337578041" "Composition"
//
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Hellfire Aura
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2648838997" "Hellfire Aura"
// DisplayHelp :
"P751654362" "You can control the forces of Hell to create a protective barrier around yourself, and have bound a demon to your service. This powerset has very strong resistance to fire damage, and also has a high offensive potential."
// -------------------------------------------------------------------------------- 
// Power : Fire Shield
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P3602062519" "While this power is active, Fire Shield gives you and those around you good resistance to Lethal, Smashing and Fire damage. Fire Shield also provides minimal resistance to Cold damage as well as protecting you and your partners from Disorient effects. "
// -------------------------------------------------------------------------------- 
// Power : Healing Flames
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P2452612224" "You can concentrate for a few moments to heal yourself and your allies. The power of the flames also grant protection from Toxic Damage for a while."
// -------------------------------------------------------------------------------- 
// Power : Plasma Shield
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P320120520" "While this power is active, you are surrounded by pure plasma. The Plasma Shield gives you and your allies resistance to Energy, Negative Energy, and Fire damage. Plasma Shield also gives you and your partners protection from Sleep and Hold effects. "
// -------------------------------------------------------------------------------- 
// Power : Fiery Embrace
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P2037304043" "Significantly boosts the damage of all your and your Demons' Fire attacks for quite a while. Also increases the damage of all your other non-fire based attacks for a short while."
// -------------------------------------------------------------------------------- 
// Power : Hellish Transformation
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1178955264" "Hellish Transformation"
// DisplayShortHelp :
"P4039778946" "Special, Merge with Demons"
// DisplayHelp (Power Help Text) :
"P4147921292" "You have taken the demons you summon into yourself, allowing you to wield their Hellfire directly as a Demon Lord. This increases your resistance to Lethal, Smashing, Fire, Cold and Toxic damage, as well as protection from Fear and a host of hellish attacks."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Natural Instinct
// -------------------------------------------------------------------------------- 
// DisplayName :
"P754651892" "Natural Instinct"
// DisplayHelp :
"P2761383659" "You have linked yourself to nature through a bond with a Dire Wolf, granting you that ability to bend it to your will. You can use this force to heal yourself and allies. Some powers in this set provide Bloom, which augments your healing abilities."
// -------------------------------------------------------------------------------- 
// Power : Summon Dire Wolf
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P317081537" "You call upon the aid of the fabled Dire Wolf. It has powerful bite and breath attacks. Unlike wolves and lions, the Dire Wolf has some limited ranged attacks. The Dire Wolf has good defense to Melee, Ranged and AoE attacks and good resistance to Cold damage. You may only have 1 Dire Wolf under your control at any given time. If you attempt to summon another Dire Wolf the power will fail."
// -------------------------------------------------------------------------------- 
// Power : Reconstruction
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P2130424238" "PBAoE Ally Heal, +Resistance(Toxic), +1 Bloom"
// DisplayHelp (Power Help Text) :
"P3409809199" "Through perfect control of your body, you can concentrate for a few moments and heal those around you. The effects of Reconstruction also grant resistance to Toxic damage for a while and a stack of Bloom."
// -------------------------------------------------------------------------------- 
// Power : Integration
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3486504328" "Toggle: Self +Resistance(Disorient, Hold, Sleep, Immobilize, Knockback), AOE Ally +Regeneration "
// DisplayHelp (Power Help Text) :
"P870054195" "You can Integrate your mind and body, making you and your partner resistant to Knockback, Disorient, Hold, Sleep, and Immobilization effects, as well as increase the regeneration rate of all nearby allies, for as long as you can keep this toggle power active."
// -------------------------------------------------------------------------------- 
// Power : Instant Healing
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3713351444" "PBAoE Ally +Regeneration"
// DisplayHelp (Power Help Text) :
"P2851860656" "When you activate this power, you and those around you can regenerate your health at an astounding rate. This boost to your Regeneration Rate lasts about a minute and takes a long time to recharge once used."
// -------------------------------------------------------------------------------- 
// Power : Revive
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P1840904556" "Click: PBAoE Self and Ally Resurrect"
// DisplayHelp (Power Help Text) :
"P1962691160" "Should you fall in battle, you can Revive yourself from the brink of death, unleashing a rush of healing energy in the process. You and other fallen allies around you will revive with most of your Hit Points and half your Endurance and be protected from XP Debt for 90 seconds. You will also have 15 seconds of immunity to most damage. "
// -------------------------------------------------------------------------------- 
// Power : Primal Form
// -------------------------------------------------------------------------------- 
// DisplayName :
"P442733025" "Primal Form"
// DisplayShortHelp (Mouseover) :
"P1087378198" "Special, Merge with Dire Wolf"
// DisplayHelp (Power Help Text) :
"P3015029121" "You can become one with your Dire Wolf, granting you its teeth and claws, as well as bonuses to defense against ranged, melee and AoE attacks, protection from Confuse and Placate, increased movement speed, and resistance to cold, lethal and smashing damage."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Nether Force
// -------------------------------------------------------------------------------- 
// DisplayName :
"P4022775679" "Nether Force"
// DisplayHelp :
"P2340395656" "You have become connected to a powerful being of the Netherworld known as a Lich, who has granted you access to the Netherworld's protective energy in exchange for anchoring it to our plane."
// -------------------------------------------------------------------------------- 
// Power : Dark Embrace
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P2681633570" "Toggle: Self and Partner +Res(Smash, Lethal, Negative, Toxic)"
// DisplayHelp (Power Help Text) :
"P1256096602" "You tap into the energy of the Netherworld to protect yourself and your Partner from damage. This Dark Embrace shrouds you and grants resistance to Lethal, Smashing, Negative Energy and Toxic damage."
// -------------------------------------------------------------------------------- 
// Power : Murky Cloud
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3220034228" "Toggle: PBAoE Self and Partner +Resistance(Fire, Cold, Energy, Negative, Endurance Drain) "
// DisplayHelp (Power Help Text) :
"P1087864338" "You create a Murky Cloud enshrouding you. This cloud can absorb all forms of energy, making you and your Partner more resistant to Fire, Cold, Energy, and Negative Energy attacks, as well as Endurance Drain effects. "
// -------------------------------------------------------------------------------- 
// Power : Obsidian Shield
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P2451919899" "Toggle: PBAoE Ally +Resistance(Psionic), Self +Resistance(Sleep, Hold, Disorient, Fear)"
// DisplayHelp (Power Help Text) :
"P4182336535" "You can create a special Obsidian Shield that grants good resistance to Psionic damage to those around you. With your mind enshrouded in darkness you are protected from Sleep, Fear, Hold and Disorient attacks."
// -------------------------------------------------------------------------------- 
// Power : Assume Undeath
// -------------------------------------------------------------------------------- 
// DisplayName : 
"P2139058635" "Assume Undeath"
// DisplayShortHelp (Mouseover) :
"P2723632671" "Special, Merge with Lich"
// DisplayHelp (Power Help Text) :
"P4235287675" "You have combined your power with that of your undead ally, unlocking greater powers over darkness, as well as imbuind you with enhanced resistance to Negative Energy, Cold and Toxic damage, as well as protection from Sleep and Fear effects and a set of shadowy attacks."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Ninjitsu
// -------------------------------------------------------------------------------- 
// DisplayHelp :
"P2998955237" "You are a practitioner of the arts of ninjutsu. Along with your trusted student, you are able to evade attacks and befuddle enemies."
// -------------------------------------------------------------------------------- 
// Power : Ninja Reflexes
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3861873125" "Toggle: PBAoE Ally +Def(Melee), +Res(Def Debuff)"
// DisplayHelp (Power Help Text) :
"P2236912589" "Activating the Seal of Intuition, you grant yourself and those around you a bonus to defense against melee attack and a greater resistance to defense debuffs."
// -------------------------------------------------------------------------------- 
// Power : Danger Sense
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3409798308" "Toggle: PBAoE Ally +Def(Ranged, Area of Effect), +Res(Def Debuff), +Perception"
// DisplayHelp (Power Help Text) :
"P3014511944" "The Seal of Awareness grants you and nearby allies a bonus to defense against ranged and area attacks while active, as well as enhancing perception and resistance to defense debuffs."
// -------------------------------------------------------------------------------- 
// Power : Kuji-In Rin
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P1400518892" "Kuji-In Rin is the strength of mind and body. By focusing your power on this exercise, you and your Jounin gain a resistance to Disorient, Hold, Sleep, Immobilization, Confusion, and Fear, as well as resistance to Psionic damage for a few minutes. "
// -------------------------------------------------------------------------------- 
// Power : Kuji-In Sha
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P1949928212" "Click: PBAoE Ally Heal, +Res(Toxic)"
// DisplayHelp (Power Help Text) :
"P3164625867" "Kuji-In Sha invokes the power of Sha, or healing. Focusing your inner power, you can heal yourself and your allies of wounds and leave all resistant to the effects of Toxic damage for a while. "
// -------------------------------------------------------------------------------- 
// Power : Oni no Henshin
// -------------------------------------------------------------------------------- 
// Display Name
"P2629978112" "Oni no Henshin"
// DisplayShortHelp (Mouseover) :
"P4019493806" "Special, Oni Transformation"
// DisplayHelp (Power Help Text) :
"P3093783699" "Your disciples sacrifice themselves to fuel your transformation into a demon of fire and vengeance known as an Oni. Whil in this form, you wield several fiery attacks, and gain enhanced defense against melee, ranged and area attacks, resistance to Smashing, Lethal and Fire damage, enhanced Endurance recovery, protection from Confusion and Taunts, and resistance to defense debuffs."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Robotics
// -------------------------------------------------------------------------------- 
// DisplayHelp :
"P3284189322" "You have control over an Assault Bot loaded with a variety of weapons. In addition, you have several devices capable of hindering enemies or emitting protective force fields around you."
// -------------------------------------------------------------------------------- 
// Power : Deflection Shield
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P1710388808" "Toggle: PBAoE, Ally +DEF(Smash, Lethal, Melee), +Res(Toxic)"
// DisplayHelp (Power Help Text) :
"P1882102583" "Dramatically protects you and nearby allies from Smashing, Lethal and all Melee attacks while active. Also reduces Toxic damage."
// -------------------------------------------------------------------------------- 
// Power : Insulation Shield
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P2299597199" "Toggle: PBAoE Ally +DEF(Fire, Cold, Energy, Negative, Ranged, AoE), +Res(End Drain)"
// DisplayHelp (Power Help Text) :
"P3880114694" "Dramatically protects you and allies from Fire, Cold, Energy, Negative Energy, Ranged and AoE attacks while active. The Insulation also protects the target from Endurance Draining effects."
// -------------------------------------------------------------------------------- 
// Power : Repair
// -------------------------------------------------------------------------------- 
// DisplayHelp (Power Help Text) :
"P342572899" "You can release a small swarm of nanites that can Repair your Assault Bot to full health and restores some of its Endurance. This power only works on your Assault Bot partner."
// -------------------------------------------------------------------------------- 
// Power : Armor Protocol
// -------------------------------------------------------------------------------- 
// Display Name
"P2259517410" "Armor Protocol"
// DisplayShortHelp (Mouseover) :
"P1493065189" "Special, Merge with Assault Bot"
// DisplayHelp (Power Help Text) :
"P2479789803" "You can wrap yourself in your assault bot like an exoskeleton, offering you direct access to its weapons and defenses, as well as a thick layer of protection. You gain protection from Sleep, Fear, and Stun effects, resistance to Lethal, Cold, and Psionic damage, and a significant amount of Absorb."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Streetwise
// -------------------------------------------------------------------------------- 
// DisplayName :
"P4149362117" "Streetwise"
// DisplayHelp :
"P3877431251" "Your charisma and determination allow you to push your allies forward and have attracted the loyalty of a Bruiser. This powerset is an all-around effective set with strong group buffs."
// -------------------------------------------------------------------------------- 
// Power : Mind Over Body
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P1444489732" "Toggle: PBAoE Ally +Resistance(Smashing, Lethal, Psionic)"
// DisplayHelp (Power Help Text) :
"P2213276857" "When you toggle on this power, you empower your allies' Mind Over Body to become highly resistant to Smashing, Lethal and Psionic damage."
// -------------------------------------------------------------------------------- 
// Power : Indomitable Will
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P163431477" "Toggle: PBAoE Ally +Defense(Psionic), Self +Res(Disorient, Hold, Sleep, Fear, Confusion, Knockback)"
// DisplayHelp (Power Help Text) :
"P2684890606" "When you toggle on this power, it grants you and your partner protection from Sleep, Disorient, Fear, Confusions, Repel, Knockback and Hold effects. Indomitable Will also grant a moderate defense to Psionic based attacks to all nearby allies. "
// -------------------------------------------------------------------------------- 
// Power : Rally
// -------------------------------------------------------------------------------- 
// Display Name
"P2788631719" "Rally"
// DisplayShortHelp (Mouseover) :
"P1139366202" "PBAoE: Ally +Absorb, +Regeneration"
// DisplayHelp (Power Help Text) :
"P541216686" "You can rally your friends and your partner to victory, giving them an Absorb shield and a bonus to regeneration."
// -------------------------------------------------------------------------------- 
// Power : Call Everybody
// -------------------------------------------------------------------------------- 
// Display Name
"P1757268311" "Call Everybody"
// DisplayShortHelp (Mouseover) :
"P2512820719" "Summon Gang"
// DisplayHelp (Power Help Text) :
"P4247907385" "You put out a call for the roughest guys in the neighborhood. This summons five local ruffians, who will aid you for a few minutes. They take orders better than the average guy, and can even be enhanced with your own powers!"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Super Serum
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3409802089" "Super Serum"
// DisplayHelp :
"P1993497039" "You have created a super serum that has grant you and your Commando partner, a fellow beneficiary of the serum, extreme durability and a defensive aura. This set has high resistance to most damage types, as well as potent offensive debuffs as you learn to unlock the serum's properties."
// -------------------------------------------------------------------------------- 
// Power : Temp Invulnerability
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3330653477" "Toggle: PBAoE Ally +Res(Smashing, Lethal)"
// DisplayHelp (Power Help Text) :
"P3276870019" "When you toggle on this power, you perspire a vapor that causes you and those around you to become highly resistant to Smashing and Lethal damage."
// -------------------------------------------------------------------------------- 
// Power : Resist Elements
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3993718417" "Auto: Self and Partner +Res(Fire, Cold, Toxic, -Recharge, -Speed, -Jump)"
// DisplayHelp (Power Help Text) :
"P4139476358" "Your serum passively protects you and your Partner, granting resistance to Fire, Cold and Toxic damage, as well as resistance to Slow effects."
// -------------------------------------------------------------------------------- 
// Power : Resist Energies
// -------------------------------------------------------------------------------- 
// DisplayShortHelp (Mouseover) :
"P3036819721" "Toggle: PBAoE Ally +Res(Energy, Negative, End Drain)"
// DisplayHelp (Power Help Text) :
"P4100698844" "While this power is toggled, your serum causes create a field that confers resistance to Energy and Negative Energy damage and Endurance drain effects to you and your Partner."
// -------------------------------------------------------------------------------- 
// Power : Transmute
// -------------------------------------------------------------------------------- 
// Display Name
"P1802669341" "Transmute"
// DisplayShortHelp (Mouseover) :
"P1379947600" "Special, Mutate Self and Partner"
// DisplayHelp (Power Help Text) :
"P392358043" "You have perfected a serum to a point that  you can briefly turn both yourself and your Commando into hideous but powerful monsters bonuses to Damage and To Hit. However, when the formula wears off, you are both left with reduced Defense, drained of some of your Endurance, and your attacks are substantially weakened."
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Mental Projection
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3455256583" "Mental Projection"
// DisplayHelp :
"P2021209852" "You can project your will onto those around you, establishing telepathic defenses for yourself and others and using an astral Doppleganger of yourself to fight."
// -------------------------------------------------------------------------------- 
// Power : Doppleganger
// -------------------------------------------------------------------------------- 
// Display Name
"P1392446365" "Doppleganger"
// DisplayShortHelp (Mouseover) :
"P1935666599" "Summon Astral Double"
// DisplayHelp (Power Help Text) :
"P1572684069" "This power summons a doppleganger from your mind to assist you. Although made of thought, the Doppleganger is tangible and has powerful Energy attacks. The Doppleganger can also fly and summon Phantasms. The Phantasms are intangible, and cannot be harmed. The Phantasms' attacks deal illusory damage similar to that dealt by Spectral Wounds. Only the original Doppleganger can be commanded, healed and buffed."
// -------------------------------------------------------------------------------- 
// Power : Daze
// -------------------------------------------------------------------------------- 
// Display Name
"P2486154698" "Daze"
// DisplayShortHelp (Mouseover) :
"P2132242576" "Ranged (Cone): Foe Stun"
// DisplayHelp (Power Help Text) :
"P1651619034" "You can project a burst of psychic noise that render targets disoriented."
// -------------------------------------------------------------------------------- 
// Power : Mass Placate
// -------------------------------------------------------------------------------- 
// Display Name
"P2279158496" "Mass Placate"
// DisplayShortHelp (Mouseover) :
"P3415948755" "Click: PBAoE Foe Placate"
// DisplayHelp (Power Help Text) :
"P2973061334" "You can exude a wave of calm that forces enemies to stop fighting momentarily, Placating them. They will be able to attack you again if you attack them."
// -------------------------------------------------------------------------------- 
// Power : Astral Form
// -------------------------------------------------------------------------------- 
// Display Name
"P1657628533" "Astral Form"
// DisplayShortHelp (Mouseover) :
"P2335305095" "Special, Assume Astral Form"
// DisplayHelp (Power Help Text) :
"P2437706068" "You push your psychic power to the limit, transforming you into a psychic being that exudes a protective aura and can strike terror into enemies. Afterward, you are left drained of most of your endurance and endurance recovery for a while."
