// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Supernatural Defense 
// -------------------------------------------------------------------------------- 
// DisplayName :
"P266738810" "Supernatural Defense"

// -------------------------------------------------------------------------------- 
// Power : Supernatural Healing
// -------------------------------------------------------------------------------- 
// DisplayName :
"P323223073" "Supernatural Healing"

// -------------------------------------------------------------------------------- 
// Power : Supernatural Resistance
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1664719748" "Supernatural Resistance"

// -------------------------------------------------------------------------------- 
// Power : Supernatural Endurance
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2114808904" "Supernatural Endurance"

// -------------------------------------------------------------------------------- 
// Power : Shadow Wolf
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2239889498" "Shadow Wolf"

// -------------------------------------------------------------------------------- 
// Power : Loup Garou
// -------------------------------------------------------------------------------- 
// DisplayName :
"P395628830" "Loup Garou"


// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Supernatural Melee 
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1956934012" "Supernatural Melee"

// -------------------------------------------------------------------------------- 
// Power : Savage Strike
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P4100731615" "Savage Strike"

// -------------------------------------------------------------------------------- 
// Power : Maiming Slash
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P898882958" "Maiming Slash"

// -------------------------------------------------------------------------------- 
// Power : Shred
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P1109597047" "Shred"
// DisplayHelp :
"P2316772037" "A pound of Flesh"

// -------------------------------------------------------------------------------- 
// Power : Taunt
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P1980192711" "Taunt"

// -------------------------------------------------------------------------------- 
// Power : Vicious Slash
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P1246734045" "Vicious Slash"

// -------------------------------------------------------------------------------- 
// Power : Blood Thirst
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P3105194080" "Blood Thirst"
// DisplayHelp :
"P431035080" "You like it raw!"
// DisplayAttackerHit :
"P2210911250" "It ends now!"

// -------------------------------------------------------------------------------- 
// Power : Rending Flurry
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P858516965" "Rending Flurry"

// -------------------------------------------------------------------------------- 
// Power : Hemorrhage
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P723020678" "Hemorrhage"

// -------------------------------------------------------------------------------- 
// Power : Savage Leap 
// -------------------------------------------------------------------------------- 
// DisplayShortHelp :
"P1339193839" "Savage Leap"






// -------------------------------------------------------------------------------- 
// Power : Rending Flurry Normal 
// -------------------------------------------------------------------------------- 
// Display Name :
"P1794630181" "Rending Flurry Normal"
// Power Mouse-Over Text :
"P4228970349" "PBAoE, Moderate DMG(Lethal), Foe Minor DoT(Lethal), -Blood Frenzy"
// Power Help Text :
"P1444424222" "You wildly slash at nearby foes to deal moderate lethal damage and cause minor lethal damage over time. This power consumes all Blood Frenzy and will deal additional damage per stack of Blood Frenzy consumed. If you have 5 stacks of Blood Frenzy while activating this power, its radius is greatly increased, but causes you to become Exhausted for a short time. While exhausted you cannot gain Blood Frenzy. Damage: Moderate, Minor DoT, Recharge: Long"
// DisplayTargetShortHelp :
"P2103286178" "Minor DoT(Lethal)"
// DisplayTargetHelp :
"P2734086620" "You are bleeding!"
// Effect AttackerHit Message :
"P164226241" "You slash at {PlayerDest} with your {PowerName} for {Damage} points of lethal damage!"
// Effect VictimHit Message :
"P2450770963" "{PlayerSource} slashes at your with their {PowerName} for {Damage} points of Lethal damage."
// Effect AttackerHit Message :
"P740901158" "Your {PowerName} causes {PlayerDest} to bleed for {Damage} points of Lethal damage."
// Effect VictimHit Message :
"P1204045149" "{PlayerSource} causes you to bleed for {Damage} points of lethal damage."
// Effect AttackerHit Message :
"P780135143" "You burn {PlayerDest} with your Fiery Embrace for {Damage} bonus points of fire damage!"
// Effect VictimHit Message :
"P125394365" "{PlayerSource} burns you for {Damage} points of bonus fire damage!"

// -------------------------------------------------------------------------------- 
// Power : Rending Flurry Large 
// -------------------------------------------------------------------------------- 
// Display Name :
"P792047515" "Rending Flurry Large"
// Effect AttackerHit Message :
"P2432555977" "You are exhausted from using the {PowerName}!"
// DisplayFloat :
"P4236885904" "Exhausted!"

// -------------------------------------------------------------------------------- 
// Power : Savage Leap AoE 
// -------------------------------------------------------------------------------- 
// Display Name :
"P2494344335" "Savage Leap AoE"
// Power Mouse-Over Text :
"P615360225" "PBAoE, Superior DMG(Lethal), Foe Minor DoT(Lethal), +3 Blood Frenzy, Self Teleport"
// Power Help Text :
"P1938728540" "You throw yourself at your distant foes while slashing and tearing wildly dealing moderate lethal damage and causing your foes to suffer from additional minor lethal damage over time. The damage of this power can increase based on how far away you leap from, with up to double damage dealt at its strongest. Savage Leap build 1 stacks of Blood Frenzy for every 20 ft in between your target and you, up to 3 stacks. Damage: Superior, Minor DoT, Recharge: Long"