//Synergist ATOs
// Group Name:
"P0762106681" "Synergist Archetype Sets"
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P1068874" "(Synergist) Synergist's Coordination:"
// Group Name :
"P609373253" "Synergist's Coordination"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination A
// -------------------------------------------------------------------------------- 
// DisplayName :
"P225478393" "Attuned Synergist's Coordination A"
// DisplayShortHelp :
"P1906411549" "Set: Synergist's Coordination"
// DisplayHelp :
"P3122960206" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the damage of a power by {Boost.Attrib.Damage.Scale}% and accuracy by {Boost.Attrib.Accuracy.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P2234366027" "(Synergist) Synergist's Coordination: Accuracy/Damage"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination B
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2491012931" "Attuned Synergist's Coordination B"
// DisplayHelp :
"PSYNATO1B" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the damage of a power by {Boost.Attrib.Damage.Scale}% and reduces endurance cost by {Boost.Attrib.Endurance.Scale}%.  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P1068874" "(Synergist) Synergist's Coordination:"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination C
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3816744917" "Attuned Synergist's Coordination C"
// DisplayHelp :
"P1309864322" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the accuracy of a power by {Boost.Attrib.Accuracy.Scale}% and damage by {Boost.Attrib.Damage.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P681985613" "(Synergist) Synergist's Coordination: Accuracy/Damage/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination D
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2098885238" "Attuned Synergist's Coordination D"
// DisplayHelp :
"P499014271" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the damage by {Boost.Attrib.Damage.Scale}% and reduces endurance cost by {Boost.Attrib.Endurance.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P498590442" "(Synergist) Synergist's Coordination: Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination E
// -------------------------------------------------------------------------------- 
// DisplayName :
"P169689824" "Attuned Synergist's Coordination E"
// DisplayHelp :
"P709232492" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the accuracy of a power by {Boost.Attrib.Accuracy.Scale}%, damage by {Boost.Attrib.Damage.Scale}%, reduces endurance cost by {Boost.Attrib.Endurance.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P2885968658" "(Synergist) Synergist's Coordination: Accuracy/Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Synergist's Coordination F
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1043647839" "Attuned Synergist's Coordination"
// DisplayHelp :
"P3780991518" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Reduces recharge time by {Boost.Attrib.Recharge.Scale}% Additionally, while slotted in one of your attacks, that attack has a 1PPM chance to grant you a boost to damage and ToHit, and if slotted in a pet power, it grants that to the pets' attacks instead .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P325354271" "(Synergist) Synergist's Coordination: Recharge/Special Chance for Build Up"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P2872373039" "(Synergist) Superior Synergist's Coordination"
// Group Name :
"P1398496226" "Superior Synergist's Coordination"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination A
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3270190767" "Attuned Superior Synergist's Coordination A"
// DisplayShortHelp :
"P1843939393" "Set: Superior Synergist's Coordination"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P543293565" "(Synergist) Superior Synergist's Coordination: Accuracy/Damage"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination B
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1541568277" "Attuned Superior Synergist's Coordination B"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P2872373039" "(Synergist) Superior Synergist's Coordination:"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination C
// -------------------------------------------------------------------------------- 
// DisplayName :
"P753223555" "Attuned Superior Synergist's Coordination C"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P2332866506" "(Synergist) Superior Synergist's Coordination: Accuracy/Damage/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination D
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2994852384" "Attuned Superior Synergist's Coordination D"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P1858625176" "(Synergist) Superior Synergist's Coordination: Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination E
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3313951414" "Attuned Superior Synergist's Coordination E"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P1688114180" "(Synergist) Superior Synergist's Coordination: Accuracy/Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Synergist's Coordination F
// -------------------------------------------------------------------------------- 
// DisplayName :
"P3205451371" "Attuned Superior Synergist's Coordination F"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Synergist's Coordination
// -------------------------------------------------------------------------------- 
// Display Name :
"P740661741" "(Synergist) Superior Synergist's Coordination: Recharge/Special Chance for Build Up"
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P512506119" "(Synergist) Shared Victory"
// Group Name :
"P650497685" "Shared Victory"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory A
// -------------------------------------------------------------------------------- 
// DisplayName :
"P4173187091" "Attuned Shared Victory A"
// DisplayShortHelp :
"P1233759980" "Set: Shared Victory"
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P124447359" "(Synergist) Shared Victory: Accuracy/Damage"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory B
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1639225769" "Attuned Shared Victory B"
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P512506119" "(Synergist) Shared Victory: Damage/Endurance"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory C
// -------------------------------------------------------------------------------- 
// DisplayName :
"P380873023" "Attuned Shared Victory C"
// DisplayHelp :
"P1309864322" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the accuracy of a power by {Boost.Attrib.Accuracy.Scale}% and damage by {Boost.Attrib.Damage.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P2662128908" "(Synergist) Shared Victory: Accuracy/Damage/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory D
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2295807132" "Attuned Shared Victory D"
// DisplayHelp :
"P499014271" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the damage by {Boost.Attrib.Damage.Scale}% and reduces endurance cost by {Boost.Attrib.Endurance.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P484088183" "(Synergist) Shared Victory: Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory E
// -------------------------------------------------------------------------------- 
// DisplayName :
"P4291824650" "Attuned Shared Victory E"
// DisplayHelp :
"P709232492" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Enhances the accuracy of a power by {Boost.Attrib.Accuracy.Scale}%, damage by {Boost.Attrib.Damage.Scale}%, reduces endurance cost by {Boost.Attrib.Endurance.Scale}% and reduces recharge time by {Boost.Attrib.Recharge.Scale}% .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P1205450045" "(Synergist) Shared Victory: Accuracy/Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Shared Victory F
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1725521328" "Attuned Shared Victory F"
// DisplayHelp :
"P4213552862" "UNIQUE -- No more than 1 enhancement of this type may be slotted by a character.  Reduces recharge time by {Boost.Attrib.Recharge.Scale}% Additionally, while slotted in one of your attacks, that attack has a 1PPM chance to grant your pet(s) a +1 level combat shift, and if slotted in a pet power, it grants that to the pets' attacks instead .  This enhancement can only be slotted in a Synergist attack or pet power."
// -------------------------------------------------------------------------------- 
// Power : Attuned Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P4087515641" "(Synergist) Shared Victory: Recharge/Pet Combat Shift"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P1943782260" "(Synergist) Superior Shared Victory"
// Group Name :
"P230283344" "Superior Shared Victory"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory A
// -------------------------------------------------------------------------------- 
// DisplayName :
"P441307819" "Attuned Superior Shared Victory A"
// DisplayShortHelp :
"P4217090023" "Set: Superior Shared Victory"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P3574161896" "(Synergist) Superior Shared Victory: Accuracy/Damage"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory B
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2202305297" "Attuned Superior Shared Victory B"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P1943782260" "(Synergist) Superior Shared Victory:"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory C
// -------------------------------------------------------------------------------- 
// DisplayName :
"P4098077575" "Attuned Superior Shared Victory C"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P3684794411" "(Synergist) Superior Shared Victory: Accuracy/Damage/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory D
// -------------------------------------------------------------------------------- 
// DisplayName :
"P1780950564" "Attuned Superior Shared Victory D"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P3113558337" "(Synergist) Superior Shared Victory: Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory E
// -------------------------------------------------------------------------------- 
// DisplayName :
"P488642226" "Attuned Superior Shared Victory E"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P3832759482" "(Synergist) Superior Shared Victory: Accuracy/Damage/Endurance/Recharge"
// ******************************************************************************** 
// -------------------------------------------------------------------------------- 
// Power Set : Superior Shared Victory F
// -------------------------------------------------------------------------------- 
// DisplayName :
"P2217297672" "Attuned Superior Shared Victory F"
// -------------------------------------------------------------------------------- 
// Power : Attuned Superior Shared Victory
// -------------------------------------------------------------------------------- 
// Display Name :
"P1458385359" "(Synergist) Superior Shared Victory: Recharge/Pet Combat Shift"
